### ISSUE TITLE
New FLTHIST baseline with cam6_3_132

### ISSUE THREAD

**Issue by PeterHjortLauritzen** [NCAR/amwg_dev#416]
### Description of the run

New FLTHIST baseline with cam6_3_132 to approximately match coupled run 52 (https://github.com/NCAR/amwg_dev/issues/413)

Note that there is a CMEPS change that was not in coupled run 52: https://github.com/ESCOMP/CMEPS/pull/394

### Suffix in the casename

f.cam6_3_132.FLTHIST_ne30.001

### Namelist modifications

N/A

### Source modifications

N/A

### Sandbox

/glade/work/hannay/cesm_tags/cam6_3_132

### Contact info

@cecilehannay @adamrher @JulioTBacmeister

**Comment by cecilehannay** [comment]
@tilmes: I would like also to get Simone's advice on dust. Simone requested a couple of runs to tune the dust. 
I think her favorite configuration was: https://github.com/NCAR/amwg_dev/issues/393  
but we didn't include that at the time because we wanted to keep a clean comparison.
As we are doing a new baseline, it might be good to include this now.

**Comment by tilmes** [comment]
@cecilehannay I would recommend to use this, since AODDUST of 0.031 is pretty good.
dust_emis_fact = 1.3

**Comment by PeterHjortLauritzen** [comment]
See #417
