### ISSUE TITLE
control for comparing to first dribbling run

### ISSUE THREAD

**Issue by adamrher** [NCAR/amwg_dev#89]
### Description of the run

Identical to https://github.com/NCAR/amwg_dev/issues/53, but w/ cld_macmic_num_steps=6, for comparing to our first dribbling run, which also uses cld_macmic_num_steps=6.

### Namelist modifications

cld_macmic_num_steps=6

### Source modifications

DQCORE SourceMods; should be avail from https://github.com/NCAR/amwg_dev/issues/53

### Sandbox

cam6_3_041

### Contact info

@adamrher 
@JulioTBacmeister 

### Any other relevant information

Enter relevant info

**Comment by cecilehannay** [comment]
Originally, I said we would move to the new naming convention with the next tag. But I think I will update the naming. 

Either we go:
f.c6_3_41.FWscHIST.ne30_L58.001
f.c6_3_41.FWscHIST.ne30_L58.002
...

Or we have something in the name that says what the run is about:
f.c6_3_41.FWscHIST.ne30_L58_macmic6.001
f.c6_3_41.FWscHIST.ne30_L58_dribbling.001

**Comment by cecilehannay** [comment]
Or maybe, use:
f.c6_3_41.FWscHIST.ne30_L58_macmic6.001

And for the dribbling run:
f.c6_3_41_dribble.FWscHIST.ne30_L58_macmic6.001

So it makes it clear from the name that the second run is using a different tag.

**Comment by swrneale** [comment]
@hannay I would choose the former. Although given the database information I don't think we need the tag in there, but that's my personal opinion I guess. If we were to go with the latter it would be important to be disciplined with tag naming as it could get out of hand! I think the short suffix of description is useful.

**Comment by cecilehannay** [comment]
Hi @swrneale: could you clarify which one is the former. 

That say, I personally really like to include the tag names. It makes it much easier to figure out which runs are done with the same tag. And that way you are sure you compare apples to apples. Otherwise, you can end up comparing 2 different tags. And the differences could be due to the tags and not the source/namelist mods.

**Comment by JulioTBacmeister** [comment]
I don't mind longish run names.  I think a descriptive 'tag', something between 1 and 20 characters is a big help, sorting through many runs
So I prefer names along the lines of 

f.c6_3_41.FWscHIST.ne30_L58_dribbling.001

where the 'tag' is 'dribbling'

**Comment by cecilehannay** [comment]
There is a bit of mix up on the term 'tag'. By tag, I meant the cam tag. 
We could have a 'label' or 'suffix' that would be a short description. 

The naming convention would be: 
**f.$TAG.$COMPSET.$RES.$LABEL.$NUMBER**

In our example, the names would be:  
- **f.c6_3_41.FWscHIST.ne30_L58_macmic6.001**
- **f.c6_3_41_dribble.FWscHIST.ne30_L58_macmic6.001**

It shows that these two runs are exploring the 
- **cld_macmic_num_steps=6**

using two different tags: 
- **cam6_3_41** and **cam6_3_41_dribble**

**Comment by cecilehannay** [comment]
The new naming:
- **f.c6_3_41.FWscHIST.ne30_L58_macmic6.001** 
would be shorter than the current naming: 
- **f.e21.FWscHIST.ne30_L48_BL10_cam6_3_041_kzz3_zmtop75.hf.001**
but not extra short. 

I am like Julio, I don't mind longish run names. But other might disagree.

**Comment by swrneale** [comment]
The two main reasons I don't like too long run names are:
1. It messes with the ncl plot scaling and gives more real estate to the run names than the plot. Although we can accommodate this in ADF eventually.
2. Carriage returns in file listings are annoying.

The new naming length seems fine, but make sure we avoid name length creep that often happens when there are multiple spurs from a simulation line :)

**Comment by cecilehannay** [comment]
Run started:
https://github.com/NCAR/amwg_dev/issues/90
